
VMEC_file: plas_eq.nc

radial_build:
  phi_list: [0.0, 22.5, 45.0, 67.5, 90.0]
  theta_list: [0.0, 90.0, 180.0, 270.0, 360.0]
  wall_s: 1.2
  repeated: False 
  components:
    first_wall:
      thickness_matrix:
        - [5, 5, 5, 5, 5]
        - [5, 5, 5, 5, 5]
        - [5, 5, 5, 5, 5]
        - [5, 5, 5, 5, 5]
        - [5, 5, 5, 5, 5]
    breeder:
      thickness_matrix:
        - [80, 40, 20, 40, 80]
        - [50, 40, 30, 30, 50]
        - [30, 30, 25, 30, 30]
        - [50, 30, 30, 40, 50]
        - [80, 40, 20, 40, 80]
    back_wall:
      thickness_matrix:
        - [5, 5, 5, 5, 5]
        - [5, 5, 5, 5, 5]
        - [5, 5, 5, 5, 5]
        - [5, 5, 5, 5, 5]
        - [5, 5, 5, 5, 5]
    shield:
      thickness_matrix:
        - [50, 25, 15, 25, 50]
        - [30, 25, 20, 20, 30]
        - [20, 20, 15, 20, 20]
        - [30, 20, 20, 25, 30]
        - [50, 25, 15, 25, 50]
    manifolds:
      thickness_matrix:
        - [50, 50, 15, 50, 50]
        - [20, 20, 15, 20, 20]
        - [15, 15, 15, 15, 15]
        - [20, 20, 20, 20, 20]
        - [50, 50, 50, 50, 50]
    gap:
      thickness_matrix:
        - [5, 5, 5, 5, 5]
        - [5, 5, 5, 5, 5]
        - [5, 5, 5, 5, 5]
        - [5, 5, 5, 5, 5]
        - [5, 5, 5, 5, 5]
      h5m_tag: Vacuum
    vacuum_vessel:
      thickness_matrix:
        - [15, 15, 15, 15, 15]
        - [15, 15, 15, 15, 15]
        - [15, 15, 15, 15, 15]
        - [15, 15, 15, 15, 15]
        - [15, 15, 15, 15, 15]
      h5m_tag: vac_vessel

stellarator_parameters:
  num_periods: 4
  gen_periods: 1
  num_phi: 61
  num_theta: 61

magnet_coils:
  file: coils.txt
  cross_section: [circle, 20]
  start: 3
  stop: null
  sample: 6
  name: magnet_coils
  h5m_tag: magnets
  meshing: False

source_mesh_parameters:
  num_s: 11
  num_theta: 81
  num_phi: 61
  tor_ext: 90.0

export_parameters:
  exclude: []
  graveyard: False
  dir: ""
  step_export: True
  h5m_export: "Cubit"
  h5m_filename: "dagmc"
  plas_h5m_tag: "Vacuum"
  sol_h5m_tag: "Vacuum"
# Note the following export parameters are used only for Cubit H5M exports
  facet_tol: 1
  len_tol: 5
  norm_tol: null
  skip_imprinting: False
# Choose whether to use native Cubit meshing (v2023.11+) or legacy DAGMC
# workflow
  native_meshing: False
  anisotropic_ratio: 100
  deviation_angle: 5
# Note the following export parameters are used only for Gmsh H5M exports
  min_mesh_size: 5.0
  max_mesh_size: 20.0
  volume_atol: 0.00001
  center_atol: 0.00001
  bounding_box_atol: 0.00001
